server:
  port: 8761



spring:
  application:
    name: SERVICE-REGISTRY
  cloud:
    config:
      enabled: false


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
