server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CUSTOMER-SERVICE
#                fallbackuri: forward:/customerServiceFallback
        - id: SIMCARD-SERVICE
          uri: lb://SIMCARD-SERVICE
          predicates:
            - Path=/api/simcard/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: SIMCARD-SERVICE
#                fallbackuri: forward:/simcardServiceFallback

#resilience4j.circuitbreaker:
#  instances:
#    customerService:
#      failureRateThreshold: 50
#      ringBufferSizeInClosedState: 5
#      ringBufferSizeInHalfOpenState: 3
#      waitDurationInOpenState: 20s
#      automaticTransitionFromOpenToHalfOpenEnabled: true


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761

